"""Init

Revision ID: e40bb642c305
Revises: fc20ab06b158
Create Date: 2022-12-11 19:56:03.691724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e40bb642c305'
down_revision = 'fc20ab06b158'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
